# Generated by Django 3.2.25 on 2024-10-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybudapp', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='studybudapp.UserProfile'),
        ),
    ]
