# Generated by Django 3.2.25 on 2024-10-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybudapp', '0009_alter_room_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='userProfile',
        ),
    ]
