# Generated by Django 3.2.25 on 2024-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybudapp', '0013_alter_userprofile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, upload_to='userpicture/'),
        ),
    ]
