# Generated by Django 3.2.25 on 2024-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybudapp', '0016_auto_20241010_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, upload_to='user_image/'),
        ),
    ]
