# Generated by Django 3.2.25 on 2024-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybudapp', '0017_alter_userprofile_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/'),
        ),
    ]
